on: [push]
jobs:
  build_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the BRs
        uses: cabforum/build-guidelines-action@wip
        with:
          markdown-file: docs/BR.md
          pdf: true
          docx: true
          lint: true
          draft: true
      - uses: actions/upload-artifact@v2
        with:
          name: BR.pdf
          path: docs/BR.pdf
          if-no-files-found: 'error'
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: BR.docx
          path: docs/BR.docx
          if-no-files-found: 'error'
          retention-days: 1
