name: builds-docs
on: [push, pull_request_target]
jobs:
  build_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build via Pandoc
        uses: docker://pandoc/latex:2.9.2.1
        with:
          entrypoint: ./docker.sh
      - uses: actions/upload-artifact@v2
        with:
          name: BRs
          path: |
            docs/BR.pdf
            docs/BR.docx
            docs/BR.html

  build_weasy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: sudo apt-get install libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info libpangocairo-1.0-0
      - name: Setup virtualenv
        run: |
          python -m venv ./virtenv
          source ./virtenv/bin/activate
      - name: Copy fonts
        run: |
          mkdir ~/.fonts/
          echo $PWD
          ls -al
          cp -a assets/*.otf ~/.fonts/
      - name: Setup PIP
        run: |
          source ./virtenv/bin/activate
          python -m pip install --upgrade pip
          pip install -U --ignore-installed setuptools
          pip install -r requirements.txt
      - name: Setup Bundle
        run: bundle install
      - name: Build via weasyprint
        run: |
          source ./virtenv/bin/activate
          make weasy
      - uses: actions/upload-artifact@v2
        with:
          name: EVGs
          path: |
            docs/EVG.pdf
            docs/EVG.html
      - uses: actions/upload-artifact@v2
        with:
          name: NSRs
          path: |
            docs/NSR.pdf
            docs/NSR.html

