name: learn-github-actions
on: [push]
jobs:
  build_brs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build via Pandoc
        uses: docker://pandoc/latex:2.9.2.1
        with:
          entrypoint: ./docker.sh
      - uses: actions/upload-artifact@v2
        with:
          name: BRs
          path: |
            docs/BR.pdf
            docs/BR.docx
            docs/BR.html
